Feature/#7 create my page
Gollala-Inc/react-gollala-club pull request #15
Opened 2021-12-28 07:07 UTC by yl9517

마이페이지 입니다
클릭이벤트 적용을 할 줄 모르겠네요 ㅠㅠ
목요일까지 최대한 클릭이벤트 + 데이터 바인딩까지 완료해보도록 하겠습니다

2021-12-28 07:38 UTC, TaeyoonKwon requested changes

2021-12-28 07:38 UTC, TaeyoonKwon commented on src/component/input/profile.tsx
> +export class FileSelector extends React.Component<undefined, undefined>
functional 컴포넌트 구조로 변경해주세요.

2021-12-28 07:38 UTC, TaeyoonKwon commented on src/component/input/ImageInput.tsx
> +  const [selectedFile, setSelectedFile] = useState(null);
state의 타입을 지정해주세요.

2021-12-28 07:38 UTC, TaeyoonKwon commented on src/pages/My.tsx
> +const MYCLUBS = [
MY_CLUBS 가 보기 좀 더 좋아보이네요

2021-12-28 09:53 UTC, yl9517 commented
중간 커밋 상태입니다 목요일날 보완해서 다시 푸시하겠습니다

2021-12-29 02:51 UTC, TaeyoonKwon commented
PR은 기본적으로 완성된 코드의 머지를 위함이므로 미완료성 코드는 PR을 하지 않는 것이 좋습니다.

2021-12-30 02:32 UTC, Jaysok commented on src/component/link/MyPageLink.tsx
> +export default function MypageButton({
Camel Case를 지켜주세요

2021-12-30 03:06 UTC, Jaysok commented on src/pages/My.tsx
> +            ></MypageButton>
`{MY_CLUBS.map(el => (<MypageButton {...el} />)}` 로 줄일 수 있을 것 같습니다.

2021-12-30 03:29 UTC, Jaysok commented on src/setupProxy.ts
> +    createProxyMiddleware({
local 개발 서버 용으로 추가를 하신 듯 한데, `package.json`에 `proxy: http://localhost:3000`을 추가하는 것으로 간단하게 해결이 가능합니다. 아래는 해당 내용에 대한 상세입니다.

https://create-react-app.dev/docs/proxying-api-requests-in-development/

2021-12-30 08:11 UTC, merged